---
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "marketplace-assistant.infinity-service-name" . }}"
spec:
  selector:
    app: infinity
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 7997
      targetPort: http
...
