apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "marketplace-assistant.knowledgebase-configmap" . }}
data:
  settings.yaml: |-
{{ include "marketplace-assistant.knowledgebase-config" . | indent 4 }}
