---
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "marketplace-assistant.vllm-service-name" . }}"
spec:
  selector:
    app: vllm
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: http
...
