name: Helm Lint
on:
  push:
    branches:
    - main
  pull_request:
  workflow_call:

jobs:
  helm-lint:
    name: Helm Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download dependencies
      run: |
        helm dependency build charts/marketplace-assistant

    - name: helm-check
      uses: igabaydulin/helm-check-action@0.2.1
      env:
        CHART_LOCATION: charts/marketplace-assistant
        CHART_VALUES: tests/helm-lint/marketplace-assistant/dummy-values.yml
